server:
  host: "0.0.0.0"
  port: 8080

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  database: "dynagate"

ldap:
  url: ""
  base_dn: ""
  bind_dn: ""
  bind_password: ""
  user_dn: "ou=users"
  group_dn: "ou=groups"

etcd:
  endpoints:
    - "127.0.0.1:2379"
  timeout: 5
  username: "root"
  password: "xxxx"
  ca_cert: ""
  cert: ""
  key: ""