server:
  host: "0.0.0.0"
  port: 8080

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  database: "dynagate"

ldap:
  url: "https://172.18.66.181:2379"
  base_dn: "ou=EtcdxsCloudglab,dc=cloudglab,dc=com"
  bind_dn: "cn=readonly,ou=EtcdxsCloudglab,dc=cloudglab,dc=com"
  bind_password: "dIPXCAGSAw12gSPAonialuWa46DnJFiG"
  user_dn: "ou=users"
  group_dn: "ou=groups"

etcd:
  endpoints:
    - "172.18.66.181:2379"
  timeout: 5
  username: "root"
  password: "yskj.2022."
  ca_cert: "/Users/chenzm/Documents/DynaGate/ssl/ca.pem"
  cert: "/Users/chenzm/Documents/DynaGate/ssl/etcd.pem"
  key: "/Users/chenzm/Documents/DynaGate/ssl/etcd-key.pem"